STATE_WINDOW = 1
CONVS = []
PADDING='VALID'
FCS = [64, 64]
LSTM_UNIT = 64
FINAL_STEP = 10 ** 6

LSTM = True
POLICY_FACTOR = 1.0
VALUE_FACTOR = 0.5
ENTROPY_FACTOR = 0.01
LR = 7e-4
LR_DECAY = 'linear'
GRAD_CLIP = 40.0
TIME_HORIZON = 5
GAMMA = 0.99
OPTIMIZER = 'rmsprop'

EVAL_INTERVAL = 10 ** 5
EVAL_EPISODES = 5
RECORD_EPISODES = 3
